### ISSUE TITLE
Downloading this on macOS

### ISSUE THREAD

**Issue by AadiPatangi** [Awesomeplayer165/SwiftUI-Weather#1]
Where on macos can I download this as the README.md says that this is optimized for macos?

**Comment by Awesomeplayer165** [comment]
Sorry. I have not meant for this to be downloaded as an app - you would have to download the Xcode project and compile it yourself. Let me know if you want me to export the app in a .app format (for macOS)

**Comment by AadiPatangi** [comment]
> Sorry. I have not meant for this to be downloaded as an app - you would have to download the Xcode project and compile it yourself. Let me know if you want me to export the app in a .app format (for macOS)

In that case, I suggest changing the wording of the README.md

**Comment by Awesomeplayer165** [comment]
Okay I will, thanks for the suggestion. Just to be clear:

The `README.md` does not mention any of the sort about the `.app` available for download. It was optimized for macOS, as in the compiled result looks nice on macOS
